config/routes.rb
Rails.application.routes.draw do  resources :employees

  root 'employees#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :subordinates, class_name: "Employee",
                          foreign_key: "manager_id"
  has_one :phone, dependent: :destroy                        
  belongs_to :manager, class_name: "Employee"
  
  default_scope { order('last_name, first_name')}
  scope :without_ids, ->(ids) { where('id not in (?)', ids) }

  validates :first_name, :last_name, presence: true
  validates_associated :phone

  accepts_nested_attributes_for :phone

  before_destroy :update_subordinates

  def self.all_subordinates(employee)
    @subordinates_array ||= []
    sub_ordinates = employee.subordinates
    @subordinates_array += sub_ordinates.all
    sub_ordinates.each{ |empl| all_subordinates(empl) }
    @subordinates_array
  end

  def full_name
    [last_name, first_name].join(' ')
  end

private
    
  def update_subordinates
    self.subordinates.update_all(manager_id: nil)
  end

end

app/models/phone.rb
class Phone < ActiveRecord::Base
	belongs_to :employee
	validates :number, presence: true
	validates_format_of :number, with: /\+7\s?\(\d{3}\)\s?\d{3}\-\d{2}\-\d{2}/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	layout 'staff'
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
    @employee.phone = Phone.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee, notice: t('helpers.notices.created')
    else
      render :new
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee, notice: t('helpers.notices.updated')
    else
      render :edit
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_url, notice: t('helpers.notices.destroyed')
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :manager_id, phone_attributes: [:number ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
	def manager_collection(employee)
		subordinate_ids = Employee.all_subordinates(employee).map(&:id) << employee.id.to_i
    Employee.without_ids(subordinate_ids).map{ |e| [e.full_name, e.id]}
	end
end

app/views/employees/_form.html.haml
.row
  .col-xs-5
    = simple_form_for @employee, :html => { :class => 'form-horizontal validatable-form' } do |f|
      = f.input :first_name, input_html: {id: "first_name", placeholder: "Имя", type: 'text', 'data-msg-minlength' => 'Поле не может быть пустым', 'data-rule-minlength' => '1', 'data-rule-maxlength' => '256', 'data-rule-required' => "true"}
      .help-block
        Пример: Иван
      = f.input :last_name, input_html: {id: "last_name", placeholder: "Фамилия", type: 'text', 'data-msg-minlength' => 'Поле не может быть пустым', 'data-rule-minlength' => '1', 'data-rule-maxlength' => '256', 'data-rule-required' => "true"}
      .help-block
        Пример: Иванов
      = f.simple_fields_for :phone do |fp|
        = fp.input :number, type: :tel, input_html: {id: "number", placeholder: "Номер телефона", type: 'text', 'data-msg-minlength' => 'Поле не может быть пустым', 'data-rule-minlength' => '1', 'data-msg-regex' => 'Должен иметь формат: +7 (xxx) xxx-xx-xx', 'data-rule-regex' => "\+7\s?\(\d{3}\)\s?\d{3}\-\d{2}\-\d{2}", 'data-rule-required' => "true"}
        .help-block
          Должен иметь формат: +7 (xxx) xxx-xx-xx
      = f.association :manager, collection: manager_collection(@employee), input_html: {id: "manager"}
      %br
      = f.button :submit, :type => "submit", :class => 'btn btn-primary'
      = link_to t("helpers.links.cancel"), employees_path, :class => 'btn btn-default'

app/views/employees/edit.html.haml
- model_class = Employee
.page-header
  %h1= t '.title'

= render :partial => 'form'

app/views/employees/index.html.haml
- model_class = Employee
.page-header
  %h1= t '.title'
= link_to t('.new'), new_employee_path, :class => 'btn btn-primary'                           
%br
%br
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th= model_class.human_attribute_name(:full_name)
      %th= model_class.human_attribute_name(:subordinates)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @employees.each do |employee|
      %tr
        %td= link_to employee.full_name, employee_path(employee)
        %td= employee.subordinates.count
        %td
          = link_to t('helpers.links.edit'), edit_employee_path(employee), :class => 'btn btn-default btn-xs'
          = link_to t('helpers.links.destroy'), employee_path(employee), :method => :delete, :data => { :confirm => t("helpers.links.confirm") }, :class => 'btn btn-xs btn-danger'                                                                          

app/views/employees/new.html.haml
- model_class = Employee
.page-header
  %h1= t '.title'
= render :partial => 'form'

app/views/employees/show.html.haml
.page-header
  %h1= t '.title'
%dl.dl-horizontal
  %dt
    %strong
      = Employee.human_attribute_name(:full_name)
      \:
  %dd= @employee.full_name
  %dt
    %strong
      = Phone.human_attribute_name(:number)
      \:
  %dd= @employee.phone.number
  - manager = @employee.manager  
  - if manager
    %dt
      %strong
        = Employee.human_attribute_name(:manager)
        \:
    %dd
      = link_to manager.full_name, employee_path(manager)
    %dt
      %strong
        = Phone.human_attribute_name(:number)
        \:
    %dd= manager.phone.number
- subordinates = @employee.subordinates
- if subordinates.any?
  %p
    %b
      = Employee.human_attribute_name(:subordinates_list)
      \:   
  - @employee.subordinates.each do |subordinat|
    %dl.dl-horizontal
      %dt
        %strong
          = Employee.human_attribute_name(:full_name)
        \:
      %dd= link_to subordinat.full_name, employee_path(subordinat)
      %dt
        %strong
          = Phone.human_attribute_name(:number)
          \:
      %dd= subordinat.phone.number
= link_to t('.back', :default => t("helpers.links.back")), employees_path, :class => 'btn btn-default'              
= link_to t('.edit', :default => t("helpers.links.edit")), edit_employee_path(@employee), :class => 'btn btn-default' 
= link_to t('.destroy', :default => t("helpers.links.destroy")), employee_path(@employee), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'                                                                                   |

app/views/layouts/staff.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Staff"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => employees_path} Главная
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield